# Copy of pod.yaml without file extension for test
apiVersion: v1
kind: Pod
metadata:
  name: tomcat
  labels:
    name: tomcat
spec:
  containers:
  - name: nginx
    image: 192.168.25.187:80/dcos/tomcat
    ports:
    - containerPort: 8080
